### ISSUE TITLE
false to set g:rg_derive_root to True

### ISSUE THREAD

**Issue by tuyenpm9** [jremmen/vim-ripgrep#12]
I'm trying to make rg to search on top of project instead of current opened buffer.
but try to set `let g:rg_derive_root = True` doesn't work.

gvim 8.0 on windows 10.

**Comment by tuyenpm9** [comment]
set = 1 is work but i find vim-rooter plugin to change root instead.

**Comment by watsoncj** [comment]
To clarify for others, the correct syntax is:

`let g:rg_derive_root = 1`
