### ISSUE TITLE
vim-ripgrep is ignoring .gitignore by default but not in shell

### ISSUE THREAD

**Issue by ar1xwe** [jremmen/vim-ripgrep#20]
Hi. I've encounter a problem with vim-ripgrep.

It automatically ignore my '.gitignore' file.

Root: D:\MyFolder
List:
MyFolder\.gitignore
  '''
  \*.zxc
  bar.\*
  '''
MyFolder\foo.zxc
  '''Lorem Ipsum'''
MyFolder\foo.xcv
  '''Lorem Ipsum'''
MyFolder\bar.zxc
  '''Lorem Ipsum'''

Command:
    rg -g *.zxc -e "Lorem Ipsum"
->
Bash output:
    1:Lorem Ipsum
->
Vim output: (with --vimgrep)
    bar.zxc|1 col 1| Lorem Ipsum
    foo.zxc|1 col 1| Lorem Ipsum

Any idea how to solve this problem?

I've did
- [ v ] Make sure bash / vim using same switch except --vimgrep
- [ v ] Update ripgrep to latest version

**Comment by jremmen** [comment]
Hi. I unsuccessfully tried to reproduce the issue you described, using the same context. I altered the `.gitignore` file and observed the changes being respected in Vim.

**Comment by ar1xwe** [comment]
I've fix this issue finally. it's some problems with window's cmd.
Thanks for reply
