### ISSUE TITLE
feature request: Have a way to pass "temporary" rg flags

### ISSUE THREAD

**Issue by n00bmind** [jremmen/vim-ripgrep#25]
Hi.
Many thanks for the plugin. I have it mapped to several keys, and it'd be really neat if I could pass each of those a slightly different subset of rg flags, without having to change any of the g: variables. For instance I'd like to have mapping for regex/nonregex, case sensitive/insensitive etc. As it stands, its a bit cumbersome to do so.
Just my two cents.
Thanks!

**Comment by watsoncj** [comment]
This used to work in 88ce3691. Was broken with the introduction of visual search selection 7d01d697.
