### ISSUE TITLE
Respect vim's options on smart-case, ignore-case, etc?

### ISSUE THREAD

**Issue by lfilho** [jremmen/vim-ripgrep#5]
Hello. Thanks for the plugin!

Just stumbled across this. I have `set smartcase` on in my .vimrc so it would be great if your plugin could be aware of those options and auto add the according flags to RG command...
What do you think?

Thanks

**Comment by jremmen** [comment]
Fixed in https://github.com/jremmen/vim-ripgrep/pull/21 release v1.0.1
