### ISSUE TITLE
Neovim Nightly - E1208: -complete used without -nargs

### ISSUE THREAD

**Issue by Trid-collab** [jremmen/vim-ripgrep#59]
NVIM v0.6.0-dev+127-g1a10acb99

I am using the latest neovim nightly mentioned above. Just after the latest neovim nightly update I noticed that I have started getting the following error. Could you please help.

Error detected while processing /home/tridib/.local/share/nvim/site/pack/packer/start/vim-ripgrep/plugin/vim-ripgrep.vim:
line  149:
E1208: -complete used without -nargs
Press ENTER or type command to continue

**Comment by ABitMoreDepth** [comment]
Also started seeing this.

**Comment by Trid-collab** [comment]
Thank you. How can I pull this. I am new to this. I gather that the edits mentioned are still not merged with the main and hence not updating the install when I am trying update the plugin with my package manager

**Comment by tsullivan** [comment]
@Trid-collab I recommend using [`hub`](https://github.com/github/hub) to check out the branch of the contributor that posted `https://github.com/jremmen/vim-ripgrep/pull/56`. 

```
cd ~/.vim/<plugins_dir>/vim-ripgrep
hub checkout https://github.com/jremmen/vim-ripgrep/pull/56
```

After the PR is merged, you'll want to reinstall the plugin or just re-checkout the master branch and pull from `origin` with `git pull origin master`

**Comment by Trid-collab** [comment]
@tsullivan thank you very much for your guidance. Its working now

**Comment by samgranieri** [comment]
@jremmen neovim 0.6 was just released, and this bit me on arch linux. Could you kindly merge this? I'm using the solution from @tsullivan
