### ISSUE TITLE
E1208: Complete used without allowing arguments.

### ISSUE THREAD

**Issue by theathleticnerd** [jremmen/vim-ripgrep#63]
line  149: E1208: -complete used without allowing argumentsPress ENTER or type command to continue
I get this error every time I open vim. I tried finding a solution online, but haven't found it yet
These are the lines used in my ~/.vimrc
if executable('rg')
    let g;rg_derive_root='true'
endif
nnoremap <leader>ps :Rg<SPACE>

**Comment by F3R70** [comment]
Modifying

`command! -complete=file RgRoot :call s:RgShowRoot()`

to

`command! -nargs=* -complete=file RgRoot :call s:RgShowRoot()`

also makes the errro go away ... not sure if its a proper solution.
