### ISSUE TITLE
Control how the quickfix window is opened

### ISSUE THREAD

**Issue by jmcomets** [jremmen/vim-ripgrep#7]
After running `:Rg`, I want the quickfix window to be opened with something like `:bot copen`.
After looking at the code, right now it's just a [`copen`](https://github.com/jremmen/vim-ripgrep/blob/master/plugin/vim-ripgrep.vim#L38), but I don't see how this couldn't be changed via an option.

**Comment by jremmen** [comment]
Added in https://github.com/jremmen/vim-ripgrep/pull/19

**Comment by jmcomets** [comment]
Thanks! I'd switched back to `ack-vim` with a custom user command because of the annoyance, definitely will give this another try. ;)
